version: '3'
services:
  udemy_dev:
    tty: true
    container_name: udemy_dev
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ~/script/python_lesson/udemy-python:/work
    ports:
      - "8888:8888"